name: cypress
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-cypress-tf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: demo-cypress-tf/package-lock.json
      - name: 📦 Install dependencies
        run: npm install
      - name: 🧪 Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: demo-cypress-tf
          start: npm start
          wait-on: 'http://localhost:3000'
      - name: Report Results
        if: false
        uses: testfiesta/tacotruck-action@v1
        with:
         provider: testfiesta
         handle: handle
         project: project
         base-url: https://staging.api.testfiesta.com
         credentials: ${{ secrets.TESTFIESTA_API_KEY }}
         run-name: Cypress CI run ${{ github.run_number }}
         results-path: ./demo-cypress-tf/reports/test-results.xml
