name: rust cargo
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
    CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-rust-cargo-tf
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: Cargo build
        run: |
          cargo install cargo-junit
          cargo build
      - name: 🧪 Test
        run: |
          cargo test --verbose
      - name: Report Results
        if: false
        uses: testfiesta/tacotruck-action@v1
        with:
         provider: testfiesta
         handle: handle
         project: project
         base-url: https://staging.api.testfiesta.com
         credentials: ${{ secrets.TESTFIESTA_API_KEY }}
         run-name: Rust cargo CI run ${{ github.run_number }}
         results-path: ./demo-rust-cargo-tf/test-results.xml
